version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm run cypress:verify
      - save-cache: 
          key: cache-{{ checksum "package.json" }}
          paths: 
            - ~/.npm
            - ~/.cache
      - run: 
          command: npm start
          background: true
      - run: npm run cypress:run

workflows:
  version: 2
  build:
    jobs:
      - test